version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/adonis-logzio

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run ESLint
          command: node_modules/.bin/eslint .

  publish:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/adonis-logzio

    steps:
      - checkout

      - run:
          name: Set npm token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - run:
          name: Publish package to npmjs.com
          command: npm publish

workflows:
  version: 2
  develop:
    jobs:
      - lint
  release:
    jobs:
      - publish:
          context: node.js package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+(\.\d+){0,2}/
